# Generated by Django 5.1.7 on 2025-06-02 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(choices=[('A', 'Premium'), ('B', 'Standard'), ('C', 'Economy')], max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='catch_photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('fisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
